language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt
script:
- python -m unittest discover tests/
deploy:
  provider: heroku
  api_key:
    secure: IUkmbruhDBU/sPhKq93yXn2X2CSvw/y9clZKD9i/F0uFoPAwZym1fHf5rhNbNGjacQl1YiIpQOc7hLlbYZ25OOeMmA8Th7vZm5CVf+Aav+A+t1BaM16w2ksur0+plVOjKfVEZVGDJQ7uRTkMFX1vs2WY4P2SDc6qqQTi+R01ytxdnRbcQ6jkct104dSwige/Jjn5bae7rsWiSK6FMzoVJ1/mgEJcB9pE93cMPLZomM3NsCs8/1cHlwTfd0tR3PDt6Mxt4RHDT1eEFY+soe9GPHUAdQanWq5NLZYGOCvhXwIk+ahuWVJMGy4AIiyX8z7FWo2yzjVV1yAeVLKBtZw8MR7NS59FVS9Tf5WGWBNT84ESdaVNhxd0YUTxcr92/nvKz5Jz/UcEJ2kT/JkSpgaSwFlmpa8oeIH5uUeoyziqYYwE427/XQJfl9muXBkT3f626+BcOy2iKT1cmEWrimaFPfZCYR8kaANJRiAZcIXeqoerG2uOm2UPYh5+1UnOnz+99M3cbEF2gIy7AdeAceMyPBdrhvQNDUH3dtIeQ9TID1CUpTlCpOEKAAH0gL4I5r0qay1ftfli0AgvPdQ/T0ZmwclXf+lW8hmffX3C2mTwHdlPuRGkjgzeVl7tOnJm/5EOG8U7lBmK9ZPQbpa2U2WHboso0myfT0wcTh6Ppiy2m6E=
  app: sdsact-msa-pilot-sales-api
  run: "python app.py"