import os

ENVVAR_KEY_API_ENDPOINT_BRANCH = 'API_ENDPOINT_BRANCH'

DEFAULT_API_ENDPOINT_BRANCH = 'http://localhost:8080'


def get_branch_api_endpoint():
    return os.getenv(ENVVAR_KEY_API_ENDPOINT_BRANCH, DEFAULT_API_ENDPOINT_BRANCH)
