import os

ENVVAR_KEY_API_ENDPOINT_BRANCH = 'API_ENDPOINT_BRANCH'
ENVVAR_KEY_API_ENDPOINT_PRODUCT = 'API_ENDPOINT_PRODUCT'

DEFAULT_API_ENDPOINT_BRANCH = 'http://localhost:8080'
DEFAULT_API_ENDPOINT_PRODUCT = 'http://localhost:8090'


def get_branch_api_endpoint():
    return os.getenv(ENVVAR_KEY_API_ENDPOINT_BRANCH, DEFAULT_API_ENDPOINT_BRANCH)


def get_product_api_endpoint():
    return os.getenv(ENVVAR_KEY_API_ENDPOINT_PRODUCT, DEFAULT_API_ENDPOINT_PRODUCT)
